version: '3.7'
services:
  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
    container_name: ylab_db_testing
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env-dev
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env-dev
    container_name: ylab_app_testing
    command: sh -c "alembic upgrade head && pytest tests/"
    depends_on:
      - db
  redis:
    container_name: ylab_redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
